[package]
name = "aquamarine-test-crate"
version = "0.1.0"
authors = ["Mike Lubinets <lubinets@advancedblockchain.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.aquamarine]
path = "../"